### PR TITLE
Assignment2.1

### PR DESCRIPTION
**Pull request by saachi-tiger**
Solved issue #8 
Created Continuous Integration under .github/workflows/ci.yml which works on conda setup, flake8 test on push to main branch

### CODE REVIEW

**Review by sarath-srinivas — CHANGES_REQUESTED** [review]
Please follow the template in 2.1.3 and make the trigger to be push on feature branch and on pr to main (not on push to main)

**Comment by abilashravi-ta** [comment]
@saachi-tiger don't make the changes directly on _GitHub_.
Make the changes in your _local_ and then push it to _remote_.

**Comment by abilashravi-ta** [comment]
> @saachi-tiger don't make the changes directly on _GitHub_. Make the changes in your _local_ and then push it to _remote_.

I believe, I've told this multiple times.

**Comment by abilashravi-ta** [comment]
Closing this _PR_ as #10 has fixed #8.

**Pull request closed without merging**
